vich_uploader:
    db_driver: orm

    mappings:
        trick_image:
            uri_prefix: /images/tricks
            upload_destination: '%kernel.project_dir%/public/images/tricks'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        user_avatar:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\UniqidNamer